<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Contoso.RiskScoring.Api</RootNamespace>
    <AssemblyName>Contoso.RiskScoring.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiskScoring.Application\RiskScoring.Application.csproj" />
    <ProjectReference Include="..\RiskScoring.Infrastructure\RiskScoring.Infrastructure.csproj" />
  </ItemGroup>
</Project>
